# Generated by Django 5.2.8 on 2025-11-28 10:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('site', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Сайт')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('countries_served', models.JSONField(blank=True, default=list, verbose_name='Обслуживаемые страны')),
            ],
            options={
                'verbose_name': 'Логистическая компания',
                'verbose_name_plural': 'Логистические компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=5, verbose_name='Иконка (emoji)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='suppliers.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['parent__id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Название')),
                ('country', models.CharField(db_index=True, max_length=100, verbose_name='Страна')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Город')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo', models.ImageField(blank=True, upload_to='suppliers/logos/%Y/%m/', verbose_name='Логотип')),
                ('video_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='YouTube-видео')),
                ('moq', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Мин. заказ (MOQ)')),
                ('moq_currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('CNY', 'CNY'), ('RUB', 'RUB')], default='USD', max_length=3, verbose_name='Валюта MOQ')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('website', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Сайт поставщика')),
                ('verification_status', models.CharField(choices=[('not_started', 'Не запущена'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('failed', 'Ошибка')], db_index=True, default='not_started', max_length=32, verbose_name='Статус проверки')),
                ('verification_score', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=4, null=True, verbose_name='Итоговый балл проверки')),
                ('is_verified', models.BooleanField(db_index=True, default=False, verbose_name='Проверен')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('verification_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия проверки')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('is_premium', models.BooleanField(default=False, help_text='Платный аккаунт поставщика', verbose_name='Премиум')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('avg_response_time_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Среднее время ответа (часы)')),
                ('quote_acceptance_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Конверсия котировок')),
                ('additional_categories', models.ManyToManyField(blank=True, related_name='additional_suppliers', to='suppliers.category', verbose_name='Дополнительные категории')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='suppliers.category', verbose_name='Категория')),
                ('logistics_options', models.ManyToManyField(blank=True, to='suppliers.logisticscompany', verbose_name='Варианты логистики')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['-is_premium', '-verification_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Страна проверки')),
                ('status', models.CharField(choices=[('not_started', 'Не запущена'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('failed', 'Ошибка')], db_index=True, default='in_progress', max_length=32, verbose_name='Статус')),
                ('fssp_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ФССП балл')),
                ('rnp_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='РНП балл')),
                ('egrul_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ЕГРЮЛ балл')),
                ('licenses_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Лицензии балл')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Итоговый балл')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Поставщик подтвержден')),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], db_index=True, max_length=16, null=True, verbose_name='Уровень риска')),
                ('checked_sources', models.JSONField(blank=True, default=dict, verbose_name='Источники')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начато')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_checks', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Проверка поставщика',
                'verbose_name_plural': 'Проверки поставщиков',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'slug'], name='suppliers_c_parent__d321d5_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['country', 'city', 'is_active'], name='suppliers_s_country_1d0221_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['category', 'is_verified', 'is_active'], name='suppliers_s_categor_20a0f3_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['verification_status'], name='suppliers_s_verific_89f744_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_premium'], name='suppliers_s_is_prem_12c7db_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcheck',
            index=models.Index(fields=['supplier', 'status'], name='suppliers_v_supplie_e1f0ee_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcheck',
            index=models.Index(fields=['country', 'risk_level'], name='suppliers_v_country_6da639_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationcheck',
            index=models.Index(fields=['is_verified', 'completed_at'], name='suppliers_v_is_veri_4cc8b2_idx'),
        ),
    ]
