# Generated by Django 5.2.7 on 2025-12-02 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('vk', 'ВКонтакте'), ('wechat', 'WeChat'), ('phone', 'Телефон'), ('email', 'Email')], max_length=20, verbose_name='Тип')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверен')),
                ('price_credits', models.PositiveIntegerField(default=1, verbose_name='Стоимость')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Контакт поставщика',
                'verbose_name_plural': 'Контакты поставщиков',
                'unique_together': {('supplier', 'contact_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ContactAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('credits_spent', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_contacts', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.suppliercontact')),
            ],
            options={
                'verbose_name': 'Доступ к контакту',
                'verbose_name_plural': 'Доступы к контактам',
                'unique_together': {('user', 'contact')},
            },
        ),
    ]
