# Generated by Django 5.2.7 on 2025-12-02 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_remove_old_contact_fields'),
    ]

    operations = [
    ]
