# Generated by Django 5.2.7 on 2025-10-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Контактный email'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон'),
        ),
    ]
